<a href="https://colab.research.google.com/github/JulianH-H/ProgramacionAvanz2025/blob/main/Corte1/Abordaje_Secuencial/DatosPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy, Panda y MatPlotlib**

**NumPy**

  Libreria externa para Python que permite procesar:

*   Arrays multidimensionales
*   Operaciones Elemento a Elemento
*   Metodos para el procesamiento de arrays
*   Operaciones matematicas como logicas, Transformaciones de Fourier, manipulacion de formas, algebra lineal y RNG

Para utilizarla debemos importar la libreria, para ello usamos el siguiente comando:

In [ ]:
import numpy as np

En caso tal de reportar error debemos instalarla en nuestros sistemas mediante pip3, de aqui en adelante la funcion numpy funcionara como np

**Arreglos de NumPy**

Los arreglos de NumPy (Ndarray) son Objetos que parted de arreglos multidimensionales, los cuales consisten en el dato actual y su metadato con la descripcion del dato guardado, son indexados desde 0


*   Cada elemento en el NdArray es un objeto de tipo dtype
*   Cada item extraido del ndarray es representado por un objeto de pyton cocomo un array escalar



**Arrays**

Usando la funcion .array() Podemos crear arrays a partir de una serie de datos (encerrados  en [])

En las presentes lineas estan los distintos usos de los arrays

In [ ]:
a = np.array([1,2,3]) # Array a partir de datos dados
print(a)

[1 2 3]


In [ ]:
#Array Multidimencional
#Cada elemento encerado en [ ], funge como fila
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
# NdArray a partir de lista
list1 = [1,2,3,4,5]
arr = np.array(list1) # Podemos usar una lista como serie de datos
print(arr)

[1 2 3 4 5]


In [ ]:
# Arrays a partir de Datos
x = [1,2,3]
# Util en conversion de datos de python a datos numpy
c = np.asarray(x) #Usando Asarray() podemos convertir la lista
print(c)

[1 2 3]


.sarray() permite tambien determinar el tipo de dato y su orden, tal que



```
# np.asarray(a, dtype = None, order = None)
```




Asi mismo podemos crear automaticamente un arreglo de manera automatica con los siguientes comandos

In [ ]:
# Array en base a rango
arr1 = np.arange(10, 100) # .arange() nos permite generar un arreglo desde un numero X hasta un numero Y
print(arr1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
# Array de 0
arr2 = np.zeros((5,5)) #Usando .zeros(). Podemos crear un array de 0 en n dimensiones
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Como tambien podemos reestructurar un array completo a nuestra manera

In [ ]:
arr3 = np.zeros(8) # Partiendo de un array cualquiera 1D
arr3d = arr3.reshape((2,2,2)) # Podemos reestrucutarlo para que sea 2*2*2, En este caso tridimencional
print(arr3)
print(arr3d)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
#Para devolver esto, o trasnformar una matriz a una sola dimension
arr4 = arr3d.ravel() # .ravel aplana la funcion
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0.]


**Vectores**

In [ ]:
# Vector Lineal Espaciado
# Podemos crear un Array espaciado con inicio, final y pasos
vector = np.linspace(0, 20, 5) # Inicio, Final, Pasos
print(vector)

[ 0.  5. 10. 15. 20.]


Asi mismo podemos Acceder arreglos (Slice y [:])


In [ ]:
# El concepto de Slice en python aplica de la misma manera en numpy
# Es construido dandole un rango de inicio y final, al igual que un rango
arr6 = np.arange(20)
arr_slice = slice(1, 10, 2) # Inicia, Para & Pasos
element2 = arr6[6]
print(arr6[arr_slice])

[1 3 5 7 9]


In [ ]:
arr7 = np.arange(20)
print(arr7[2:]) #podemos usar las mismas especificaciones de las tuplas

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Podemos averiguar hasta un index determinado
print(arr7[:15])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Asi mismo  podemos indexar numeros
Su funcion es similar a la sintaxis normal de python


In [ ]:
arr5 = np.arange(2, 20)
element = arr5[6]

print (arr5)
print(element)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
8


In [ ]:
# Podemos extraer filas y columnas en especifico usando Slicing
d = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(d)

print(d[0:2, 0:2]) # Cortando las primeras dos filas y las primeras dos columnas

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2]
 [3 4]]


**Atributos de los Array en NumPy**

In [ ]:
print(d.shape) # Devuelve la tupla con las dimensiones del arreglo
print(d.ndim) # Devuelve el numero de dimensiones del arreglo
print(a.itemsize) # Devuelve la longitud de cada arreglo en Bytes

In [ ]:
y = np.empty([3,2], dtype = int) # Creacion de un array sin inicializar con sus dimenciones y tamaño
print(y)

[[      596803866               0]
 [139077091389632 139077720269488]
 [       11653248        11694976]]


Los valores obtenidos son valores basura presentes en la direccion asignada automaticamente por .empty()

Esto es util para velocidad, puesto que la memoria de las direcciones de memoria usadas no son limpiadas

**Pandas**

Libreria de Codigo abierto que brinda herramientas para estructuras de datos y analizis de datos. Su nombre deriva de "Panel Data", Funciona para:

*  Tabular datos con columnas de tipo hetereogeneas
*  Series de datos Ordenados y desordenados
* Matrizes arbitrarias de datos con etiquetas de filas y columnas
* Cualquier forma de observacion y datos estadiscos en sets

Provee tambien tres tipos de estructuras de datos, de las cuales estan construidas sobre los arreglos de NumPy, todas las estructuras de datos son mutables



1.   Series (1D) - Etiquetadas, Arreglos homogeneos de valor inmutable.
2.   DataFrames(2D) -- Etiquetados, Estructuras de datos escritas heterogéneamente, de tamaño mutables.
3.  Paneles(3D) - Etiquetados. Arreglos de tamaño mutable.


Para poder utilizar Pandas usamos el siguiente comando:



In [ ]:
import pandas as pd

**Series**

* Una serie es un array unidimencional que almacena datos homogeneos, por ejemplo, un dato de un solo tipo

* Todos los elementos  de una serie son mutables en valores pero inmutables en tamaño

* Los indices deben ser unicos, Hashable y debe tenre la misma longitud de datos, si ningun indice se presenta usara por defecto np.arrange(n)

* Los tipos de datos deben ser mencionado, de no ser mencionados se inferiran de manera automatica.

**Creando una Serie**


In [ ]:
# Creating an empty Series
series = pd.Series() # The Series() function creates a new Series
print(series)

In [ ]:
# Creating a series from an ndarray
# Note that indexes are a assigned automatically if not specifies
arr = np.array([10,20,30,40,50])
series1 = pd.Series(arr)
print(series1)

In [ ]:
# Creating a series from a Python dict
# Note that the keys of the dictionary are used to assign indexes during conversion
data = {'a':10, 'b':20, 'c':30}
series2 = pd.Series(data)
print(series2)

In [ ]:
# Retrieving a part of the series using slicing
print(series1[1:4])

**DataFrames**

* Un DataDrame es una estructura de datos 2D donde los datos son alineados en una manera tabular, consistiendo en filas y columnas
* Un DataFrame puede ser usado con el siguiente constructor

```
pd.DataFrane(data, indice, dtype, copy)
```
* Pueden ser de distintos tipos de datos, como ndarrays, listas, constantes, series, diccionarios, etc.

* El indice de la fila y columna del data frame tendra el defecto np.arrange(n) si ningun indice es adjuntado

* Hay un Tipo de dato para cada columna

**Creando un DataFrame**


In [ ]:
# Converting a list into a DataFrame
list1 = [10, 20, 30, 40]
table = pd.DataFrame(list1)
print(table)

In [ ]:
# Creating a DataFrame from a list of dictionaries
data = [{'a':1, 'b':2}, {'a':2, 'b':4, 'c':8}]
table1 = pd.DataFrame(data)
print(table1)
# NaN (not a number) is stored in areas where no data is provided

In [ ]:
# Creating a DataFrame from a list of dictionaries and accompaying row indices
table2 = pd.DataFrame(data, index = ['first', 'second'])
# Dict keys become column lables
print(table2)

In [ ]:
# Converting a dictionary of series into a DataFrame
data1 = {'one':pd.Series([1,2,3], index = ['a', 'b', 'c']),
        'two':pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
table3 = pd.DataFrame(data1)
print(table3)
# the resultant index is the union of all the series indexes passed

**Adicion y Eliminacion de Columnas**


In [ ]:
# A new column can be added to a DataFrame when the data is passed as a Series
table3['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
print(table3)

In [ ]:
# DataFrame columns can be deleted using the del() function
del table3['one']
print(table3)

In [ ]:
# DataFrame columns can be deleted using the pop() function
table3.pop('two')
print(table3)

**Adicion y Eliminacion de Filas**

In [ ]:
# DataFrame rows can be selected by passing the row lable to the loc() function
print(table3.loc['c'])

In [ ]:
# Row selection can also be done using the row index
print(table3.iloc[2])

In [ ]:
# The append() function can be used to add more rows to the DataFrame
data2 = {'one':pd.Series([1,2,3], index = ['a', 'b', 'c']),
        'two':pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
table5 = pd.DataFrame(data2)
table5['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
row = pd.DataFrame([[11,13],[17,19]], columns = ['two', 'three'])
table6 = table5.append(row)
print(table6)

In [ ]:
# The drop() function can be used to drop rows whose labels are provided
table7 = table6.drop('a')
print(table7)

**Importando y Exportando Datos**

In [ ]:
# Data can be loaded into DataFrames from input data stored in the CSV format using the read_csv() function
table_csv = pd.read_csv('../input/Cars2015.csv')

In [ ]:
# Data present in DataFrames can be written to a CSV file using the to_csv() function
# If the specified path doesn't exist, a file of the same name is automatically created
table_csv.to_csv('newcars2015.csv')

In [ ]:
# Data can be loaded into DataFrames from input data stored in the Excelsheet format using read_excel()
sheet = pd.read_excel('cars2015.xlsx')

In [ ]:
# Data present in DataFrames can be written to a spreadsheet file using to_excel()
#If the specified path doesn't exist, a file of the same name is automatically created
sheet.to_excel('newcars2015.xlsx')

**Matplotlib**

* MatPlotLib es una libreria de Python que esta diseñada especificamente para el desarollo de graficas, tablas, etc. Para poder mostrar datos de manera interactiva

* Inspirada en MATLAB, logrando reproducir mayoria de sus funciones



In [ ]:
# Import Matplotlib submodule for plotting
import matplotlib.pyplot as plt

**Plotting en MatPlotLib**

In [ ]:
plt.plot([1,2,3,4]) # List of vertical co-ordinates of the points plotted
plt.show() # Displays plot
# Implicit X-axis values from 0 to (N-1) where N is the length of the list

In [ ]:
# We can specify the values for both axes
x = range(5) # Sequence of values for the x-axis
# X-axis values specified - [0,1,2,3,4]
plt.plot(x, [x1**2 for x1 in x]) # vertical co-ordinates of the points plotted: y = x^2
plt.show()

In [ ]:
# We can use NumPy to specify the values for both axes with greater precision
x = np.arange(0, 5, 0.01)
plt.plot(x, [x1**2 for x1 in x]) # vertical co-ordinates of the points plotted: y = x^2
plt.show()

In [ ]:
# Multiple functions can be drawn on the same plot
x = range(5)
plt.plot(x, [x1 for x1 in x])
plt.plot(x, [x1*x1 for x1 in x])
plt.plot(x, [x1*x1*x1 for x1 in x])
plt.show()

In [ ]:
# Different colours are used for different lines
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*x1 for x1 in x],
         x, [x1*x1*x1 for x1 in x])
plt.show()

**Cuadriculas**

In [ ]:
# The grid() function adds a grid to the plot
# grid() takes a single Boolean parameter
# grid appears in the background of the plot
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.show()

In [ ]:
# The scale of the plot can be set using axis()
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.axis([-1, 5, -1, 10]) # Sets new axes limits
plt.show()

In [ ]:
# The scale of the plot can also be set using xlim() and ylim()
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.xlim(-1, 5)
plt.ylim(-1, 10)
plt.show()

**Agregando Etiquetas, Titulos, etc**

In [ ]:
# Labels can be added to the axes of the plot
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

In [ ]:
# The title defines the data plotted on the graph
x = range(5)
plt.plot(x, [x1 for x1 in x],
         x, [x1*2 for x1 in x],
         x, [x1*4 for x1 in x])
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title("Polynomial Graph") # Pass the title as a parameter to title()
plt.show()

In [ ]:
# Legends explain the meaning of each line in the graph
x = np.arange(5)
plt.plot(x, x, label = 'linear')
plt.plot(x, x*x, label = 'square')
plt.plot(x, x*x*x, label = 'cube')
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title("Polynomial Graph")
plt.legend()
plt.show()

**Marcadores**

In [ ]:
x = [1, 2, 3, 4, 5, 6]
y = [11, 22, 33, 44, 55, 66]
plt.plot(x, y, 'bo')
for i in range(len(x)):
    x_cord = x[i]
    y_cord = y[i]
    plt.text(x_cord, y_cord, (x_cord, y_cord), fontsize = 10)
plt.show()

**Guardando Graficas**

In [ ]:
# Plots can be saved using savefig()
x = np.arange(5)
plt.plot(x, x, label = 'linear')
plt.plot(x, x*x, label = 'square')
plt.plot(x, x*x*x, label = 'cube')
plt.grid(True)
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title("Polynomial Graph")
plt.legend()
plt.savefig('plot.png') # Saves an image names 'plot.png' in the current directory
plt.show()