<a href="https://colab.research.google.com/github/JulianH-H/ProgramacionAvanz2025/blob/main/DatosPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy, Panda y MatPlotlib**

**NumPy**

  Libreria externa para Python que permite procesar:

*   Arrays multidimensionales
*   Operaciones Elemento a Elemento
*   Metodos para el procesamiento de arrays
*   Operaciones matematicas como logicas, Transformaciones de Fourier, manipulacion de formas, algebra lineal y RNG

Para utilizarla debemos importar la libreria, para ello usamos el siguiente comando:

In [ ]:
import numpy as np

En caso tal de reportar error debemos instalarla en nuestros sistemas mediante pip3, de aqui en adelante la funcion numpy funcionara como np

**Arreglos de NumPy**

Los arreglos de NumPy (Ndarray) son Objetos que parted de arreglos multidimensionales, los cuales consisten en el dato actual y su metadato con la descripcion del dato guardado, son indexados desde 0


*   Cada elemento en el NdArray es un objeto de tipo dtype
*   Cada item extraido del ndarray es representado por un objeto de pyton cocomo un array escalar



**Arrays**

Usando la funcion .array() Podemos crear arrays a partir de una serie de datos (encerrados  en [])

En las presentes lineas estan los distintos usos de los arrays

In [ ]:
a = np.array([1,2,3]) # Array a partir de datos dados
print(a)

[1 2 3]


In [ ]:
#Array Multidimencional
#Cada elemento encerado en [ ], funge como fila
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
# NdArray a partir de lista
list1 = [1,2,3,4,5]
arr = np.array(list1) # Podemos usar una lista como serie de datos
print(arr)

[1 2 3 4 5]


In [ ]:
# Arrays a partir de Datos
x = [1,2,3]
# Util en conversion de datos de python a datos numpy
c = np.asarray(x) #Usando Asarray() podemos convertir la lista
print(c)

[1 2 3]


.sarray() permite tambien determinar el tipo de dato y su orden, tal que



```
# np.asarray(a, dtype = None, order = None)
```




Asi mismo podemos crear automaticamente un arreglo de manera automatica con los siguientes comandos

In [ ]:
# Array en base a rango
arr1 = np.arange(10, 100) # .arange() nos permite generar un arreglo desde un numero X hasta un numero Y
print(arr1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
# Array de 0
arr2 = np.zeros((5,5)) #Usando .zeros(). Podemos crear un array de 0 en n dimensiones
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Como tambien podemos reestructurar un array completo a nuestra manera

In [ ]:
arr3 = np.zeros(8) # Partiendo de un array cualquiera 1D
arr3d = arr3.reshape((2,2,2)) # Podemos reestrucutarlo para que sea 2*2*2, En este caso tridimencional
print(arr3)
print(arr3d)

[0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
#Para devolver esto, o trasnformar una matriz a una sola dimension
arr4 = arr3d.ravel() # .ravel aplana la funcion
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0.]


**Vectores**

In [ ]:
# Vector Lineal Espaciado
# Podemos crear un Array espaciado con inicio, final y pasos
vector = np.linspace(0, 20, 5) # Inicio, Final, Pasos
print(vector)

[ 0.  5. 10. 15. 20.]


Asi mismo podemos Acceder arreglos (Slice y [:])


In [ ]:
# El concepto de Slice en python aplica de la misma manera en numpy
# Es construido dandole un rango de inicio y final, al igual que un rango
arr6 = np.arange(20)
arr_slice = slice(1, 10, 2) # Inicia, Para & Pasos
element2 = arr6[6]
print(arr6[arr_slice])

[1 3 5 7 9]


In [ ]:
arr7 = np.arange(20)
print(arr7[2:]) #podemos usar las mismas especificaciones de las tuplas

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Podemos averiguar hasta un index determinado
print(arr7[:15])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Asi mismo  podemos indexar numeros
Su funcion es similar a la sintaxis normal de python


In [ ]:
arr5 = np.arange(2, 20)
element = arr5[6]

print (arr5)
print(element)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
8


In [ ]:
# Podemos extraer filas y columnas en especifico usando Slicing
d = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(d)

print(d[0:2, 0:2]) # Cortando las primeras dos filas y las primeras dos columnas

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2]
 [3 4]]


**Atributos de los Array en NumPy**

In [ ]:
print(d.shape) # Devuelve la tupla con las dimensiones del arreglo
print(d.ndim) # Devuelve el numero de dimensiones del arreglo
print(a.itemsize) # Devuelve la longitud de cada arreglo en Bytes

In [ ]:
y = np.empty([3,2], dtype = int) # Creacion de un array sin inicializar con sus dimenciones y tamaño
print(y)

[[      596803866               0]
 [139077091389632 139077720269488]
 [       11653248        11694976]]


Los valores obtenidos son valores basura presentes en la direccion asignada automaticamente por .empty()

Esto es util para velocidad, puesto que la memoria de las direcciones de memoria usadas no son limpiadas

**Pandas**

Libreria de Codigo abierto que brinda herramientas para estructuras de datos y analizis de datos. Su nombre deriva de "Panel Data", Funciona para:

*  Tabular datos con columnas de tipo hetereogeneas
*  Series de datos Ordenados y desordenados
* Matrizes arbitrarias de datos con etiquetas de filas y columnas